# Generated by Django 5.1.2 on 2024-10-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro_usuarios', '0002_remove_usuario_idade_usuario_email_usuario_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nome',
            field=models.TextField(default='Your Name', max_length=255),
        ),
    ]
