# Generated by Django 5.2 on 2025-06-09 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSocialMedia', '0004_alter_usuario_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
