# Generated by Django 5.1.2 on 2024-10-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro_usuarios', '0003_usuario_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='enteryour@email.com', max_length=254),
        ),
    ]
